return {
  { name = "alsa-lib", version = "1.2.14", summary = "ALSA sound library (libasound)" },
  { name = "at-spi2-core", version = "2.56.1", summary = "Assistive Technology Service Provider Interface (includes ATK)" },
  { name = "avahi", version = "0.8", summary = "mDNS/DNS-SD (Bonjour) implementation" },
  { name = "btop", version = "1.4.7", summary = "Resource monitor (bpytop ported to C++)" },
  { name = "bubblewrap", version = "0.11.2", summary = "Low-level unprivileged sandboxing tool (used by Flatpak)" },
  { name = "cairo", version = "1.18.4", summary = "2D graphics library" },
  { name = "cava", version = "1.0.0", summary = "Console-based audio visualizer for ALSA, PulseAudio and PipeWire" },
  { name = "cjson", version = "1.7.19", summary = "Ultralightweight JSON parser for C (used by mango)" },
  { name = "composefs", version = "1.0.8", summary = "Composable, immutable, content-addressed filesystem (and library)" },
  { name = "ctwm", version = "4.1.0", summary = "Window manager based on TWM (with virtual workspaces)" },
  { name = "doas", version = "6.8.2", summary = "Execute commands as another user (portable OpenBSD doas)" },
  { name = "fastfetch", version = "2.66.0", summary = "Fast, feature-rich system information fetcher (neofetch successor)" },
  { name = "fftw3", version = "3.3.11", summary = "Fastest Fourier Transform in the West (double precision)" },
  { name = "firefox", version = "153.0.3", summary = "Mozilla Firefox web browser (standalone build)" },
  { name = "flatpak", version = "1.18.0", summary = "Linux application sandboxing and distribution framework" },
  { name = "fontconfig", version = "2.18.2", summary = "Font configuration and customization library" },
  { name = "freetype", version = "2.14.3", summary = "FreeType font engine library" },
  { name = "fribidi", version = "1.0.16", summary = "Bidirectional text algorithm library" },
  { name = "fvwm3", version = "1.1.5", summary = "Virtual window manager for the X Window System" },
  { name = "gdk-pixbuf", version = "2.42.12", summary = "Image loading and scaling library" },
  { name = "gpgme", version = "1.24.3", summary = "Library providing access to GnuPG crypto functions" },
  { name = "gtk3", version = "3.24.50", summary = "GTK+ 3 toolkit" },
  { name = "harfbuzz", version = "11.1.0", summary = "Text shaping library" },
  { name = "hello", version = "1.0", summary = "A tiny demonstration package for Zeta" },
  { name = "htop", version = "3.5.2", summary = "Interactive process viewer" },
  { name = "hyprland", version = "0.56.2", summary = "Dynamic tiling Wayland compositor" },
  { name = "hyprutils", version = "0.14.0", summary = "Utility library for the Hypr ecosystem" },
  { name = "iniparser", version = "4.2.6", summary = "Standalone ini-file parsing library" },
  { name = "libICE", version = "1.1.2", summary = "X11 Inter-Client Exchange (ICE) library" },
  { name = "libSM", version = "1.2.6", summary = "X11 Session Management (SM) library" },
  { name = "libX11", version = "1.8.13", summary = "X11 core client library" },
  { name = "libXau", version = "1.0.12", summary = "X authorization protocol library (X11)" },
  { name = "libXaw", version = "1.0.16", summary = "X11 Athena Widget set" },
  { name = "libXcomposite", version = "0.4.7", summary = "X11 Composite extension client library" },
  { name = "libXcursor", version = "1.2.3", summary = "X11 cursor management and image loading library" },
  { name = "libXdamage", version = "1.1.7", summary = "X11 Damage extension client library" },
  { name = "libXdmcp", version = "1.1.5", summary = "X Display Manager Control Protocol library (X11)" },
  { name = "libXext", version = "1.3.7", summary = "X11 miscellaneous extension library (Xext, MIT-SHM, DBE, etc.)" },
  { name = "libXfixes", version = "6.0.2", summary = "X11 XFixes extension client library" },
  { name = "libXfont2", version = "2.0.9", summary = "X11 font rasterization and font server client library" },
  { name = "libXft", version = "2.3.9", summary = "X11 FreeType-based font rendering library" },
  { name = "libXi", version = "1.8.2", summary = "X11 Input extension library" },
  { name = "libXinerama", version = "1.1.6", summary = "X11 Xinerama extension client library" },
  { name = "libXkbfile", version = "1.1.3", summary = "X11 XKB file manipulation library" },
  { name = "libXmu", version = "1.3.1", summary = "X11 miscellaneous utilities library (incl. libXmuu)" },
  { name = "libXpm", version = "3.5.19", summary = "X11 pixmap (XPM) image format library" },
  { name = "libXrandr", version = "1.5.5", summary = "X11 RandR extension client library" },
  { name = "libXrender", version = "0.9.12", summary = "X Render extension client library (X11)" },
  { name = "libXt", version = "1.3.1", summary = "X11 toolkit intrinsics library" },
  { name = "libXtst", version = "1.2.5", summary = "X11 Testing extension library" },
  { name = "libXxf86vm", version = "1.1.7", summary = "X11 XFree86 video mode extension library" },
  { name = "libappstream", version = "1.1.5", summary = "AppStream cross-distro software metadata library" },
  { name = "libarchive", version = "3.8.9", summary = "Library for reading/writing streaming archives" },
  { name = "libassuan", version = "3.0.2", summary = "IPC library used by GnuPG components" },
  { name = "libcurl", version = "8.21.0", summary = "URL transfer library" },
  { name = "libdaemon", version = "0.14", summary = "Lightweight C library for writing daemons" },
  { name = "libdconf", version = "0.40.0", summary = "GSettings configuration backend" },
  { name = "libdrm", version = "2.4.134", summary = "Direct Rendering Manager userspace library" },
  { name = "libepoxy", version = "1.5.10", summary = "OpenGL function pointer management library" },
  { name = "libevdev", version = "1.13.6", summary = "Wrapper library for evdev devices" },
  { name = "libevent", version = "2.1.12", summary = "Event notification library" },
  { name = "libffi", version = "3.4.6", summary = "Portable Foreign Function Interface library" },
  { name = "libfontenc", version = "1.1.9", summary = "X11 font encoding library" },
  { name = "libfuse3", version = "3.18.2", summary = "Filesystem in Userspace library (FUSE 3)" },
  { name = "libfyaml", version = "0.9", summary = "Fully featured YAML 1.2 parser and emitter" },
  { name = "libgpg-error", version = "1.51", summary = "Library defining common GnuPG error values" },
  { name = "libgudev", version = "238", summary = "GObject bindings for libudev" },
  { name = "libinput", version = "1.31.3", summary = "Input device and event processing library" },
  { name = "libjpeg-turbo", version = "3.2.0", summary = "MMX/SSE2/SMID accelerated library for manipulating JPEG images" },
  { name = "libjson-glib", version = "1.10.0", summary = "GLib-based JSON serialization library" },
  { name = "libmtdev", version = "1.1.6", summary = "Multitouch protocol translation library (mtdev)" },
  { name = "libostree", version = "2025.7", summary = "Content-addressed object storage and versioning (ostree)" },
  { name = "libpciaccess", version = "0.17", summary = "Generic PCI access library (X11)" },
  { name = "libpng", version = "1.6.47", summary = "PNG image format library" },
  { name = "libpsl", version = "0.21.5", summary = "Public Suffix List library" },
  { name = "libseccomp", version = "2.6.0", summary = "High-level interface to the Linux seccomp syscall filter" },
  { name = "libsndfile", version = "1.2.2", summary = "Library for reading and writing audio files" },
  { name = "libsoup3", version = "3.6.6", summary = "HTTP client/server library for GNOME (libsoup 3)" },
  { name = "libtdb", version = "1.4.12", summary = "Trivial database (key-value store) library" },
  { name = "libtinfo", version = "6.6", summary = "Terminfo database and terminal capability library" },
  { name = "libtirpc", version = "1.3.6", summary = "Transport Independent RPC library" },
  { name = "libwacom", version = "2.19.0", summary = "Wacom tablet database and library" },
  { name = "libxcb", version = "1.17.0", summary = "X C Binding library (X11 protocol client library)" },
  { name = "libxcvt", version = "0.1.3", summary = "Library for VESA CVT standard timing modelines" },
  { name = "libxml2", version = "2.15.3", summary = "XML C parser and toolkit" },
  { name = "libxmlb", version = "0.3.23", summary = "Library to help create and query binary XML blobs" },
  { name = "libyaml", version = "0.2.5", summary = "YAML 1.1 parser and emitter library" },
  { name = "libz", version = "1.3.2", summary = "Zlib compression library" },
  { name = "luajit", version = "2.1.1785763465", summary = "Just-in-time compiler and drop-in replacement for Lua 5.1" },
  { name = "luv", version = "1.52.1-0", summary = "libuv bindings for LuaJIT" },
  { name = "make", version = "4.4.1", summary = "GNU Make — build automation tool" },
  { name = "mango", version = "0.15.6", summary = "MangoWM: lightweight dwl-based Wayland compositor" },
  { name = "mesa", version = "25.0.6", summary = "OpenGL/EGL implementation with software rasterizer" },
  { name = "mksh", version = "R59c", summary = "MirBSD Korn Shell" },
  { name = "neovim", version = "0.12.4", summary = "Vim-fork focused on extensibility and usability" },
  { name = "nghttp2", version = "1.70.0", summary = "HTTP/2 framing layer C library" },
  { name = "nscde", version = "2.3", summary = "Not so Common Desktop Environment: retro CDE-like desktop on FVWM" },
  { name = "pam", version = "1.7.2", summary = "Pluggable Authentication Modules (libpam.so.0 + modules)" },
  { name = "pango", version = "1.56.3", summary = "Text layout and rendering library" },
  { name = "pipewire", version = "1.6.8", summary = "Multimedia processing graph and audio/video daemon" },
  { name = "pixman", version = "0.46.4", summary = "Pixel manipulation library (low-level rendering primitives)" },
  { name = "pulseaudio", version = "17.0", summary = "Network-capable sound server and client library" },
  { name = "scenefx", version = "0.5", summary = "Wayland compositor effects library (window animation/effects)" },
  { name = "sdl2", version = "2.32.10", summary = "Simple DirectMedia Layer 2 (low-level multimedia library)" },
  { name = "tree-sitter", version = "0.26.9", summary = "Incremental parsing system for programming tools" },
  { name = "unibilium", version = "2.1.2", summary = "Library to parse terminal information (terminfo)" },
  { name = "util-macros", version = "1.20.2", summary = "X.Org Autoconf macros (build-time dependency)" },
  { name = "vim", version = "9.2.0920", summary = "Modal text editor" },
  { name = "wayland", version = "1.26.0", summary = "Wayland compositor infrastructure: client/server libraries and scanner" },
  { name = "wayland-protocols", version = "1.49", summary = "Wayland protocol XML definitions (build-time data for compositors and clients)" },
  { name = "wlroots", version = "0.20.2", summary = "Modular Wayland compositor library" },
  { name = "xauth", version = "1.1.5", summary = "X authority file utility (X11)" },
  { name = "xcb-proto", version = "1.17.0", summary = "XCB protocol descriptions (build-time dependency)" },
  { name = "xdg-desktop-portal", version = "1.22.1", summary = "Desktop integration portal frontend (D-Bus)" },
  { name = "xf86-input-libinput", version = "1.5.0", summary = "X.Org input driver based on libinput" },
  { name = "xinit", version = "1.4.4", summary = "X11 server startup tool (startx/xinit)" },
  { name = "xkbcommon", version = "1.13.2", summary = "Keyboard keymap compiler and support library" },
  { name = "xkeyboard-config", version = "2.47", summary = "XKB keymap rules and symbols database" },
  { name = "xorg-server", version = "21.1.24", summary = "X.Org X server (modesetting driver, no GLX)" },
  { name = "xorgproto", version = "2025.1", summary = "Combined X.Org protocol headers (build-time dependency)" },
  { name = "xshmfence", version = "1.3.3", summary = "X11 shared memory fence library (synchronization primitives)" },
  { name = "xtrans", version = "1.5.1", summary = "X transport library (headers and pkg-config file, build-time dependency)" },
}
