return {
  { name = "cjson", version = "1.7.19", summary = "Ultralightweight JSON parser for C (used by mango)" },
  { name = "fastfetch", version = "2.66.0", summary = "Fast, feature-rich system information fetcher (neofetch successor)" },
  { name = "fontconfig", version = "2.18.2", summary = "Font configuration and customization library" },
  { name = "freetype", version = "2.14.3", summary = "FreeType font engine library" },
  { name = "fvwm3", version = "1.1.5", summary = "Virtual window manager for the X Window System" },
  { name = "hello", version = "1.0", summary = "A tiny demonstration package for Zeta" },
  { name = "hyprland", version = "0.56.2", summary = "Dynamic tiling Wayland compositor" },
  { name = "hyprutils", version = "0.14.0", summary = "Utility library for the Hypr ecosystem" },
  { name = "libICE", version = "1.1.2", summary = "X11 Inter-Client Exchange (ICE) library" },
  { name = "libSM", version = "1.2.6", summary = "X11 Session Management (SM) library" },
  { name = "libX11", version = "1.8.13", summary = "X11 core client library" },
  { name = "libXau", version = "1.0.12", summary = "X authorization protocol library (X11)" },
  { name = "libXcomposite", version = "0.4.7", summary = "X11 Composite extension client library" },
  { name = "libXcursor", version = "1.2.3", summary = "X11 cursor management and image loading library" },
  { name = "libXdamage", version = "1.1.7", summary = "X11 Damage extension client library" },
  { name = "libXdmcp", version = "1.1.5", summary = "X Display Manager Control Protocol library (X11)" },
  { name = "libXext", version = "1.3.7", summary = "X11 miscellaneous extension library (Xext, MIT-SHM, DBE, etc.)" },
  { name = "libXfixes", version = "6.0.2", summary = "X11 XFixes extension client library" },
  { name = "libXfont2", version = "2.0.9", summary = "X11 font rasterization and font server client library" },
  { name = "libXft", version = "2.3.9", summary = "X11 FreeType-based font rendering library" },
  { name = "libXinerama", version = "1.1.6", summary = "X11 Xinerama extension client library" },
  { name = "libXmu", version = "1.3.1", summary = "X11 miscellaneous utilities library (incl. libXmuu)" },
  { name = "libXpm", version = "3.5.19", summary = "X11 pixmap (XPM) image format library" },
  { name = "libXrandr", version = "1.5.5", summary = "X11 RandR extension client library" },
  { name = "libXrender", version = "0.9.12", summary = "X Render extension client library (X11)" },
  { name = "libXt", version = "1.3.1", summary = "X11 toolkit intrinsics library" },
  { name = "libdrm", version = "2.4.134", summary = "Direct Rendering Manager userspace library" },
  { name = "libffi", version = "3.4.6", summary = "Portable Foreign Function Interface library (Zeta build-from-source sample)" },
  { name = "libfontenc", version = "1.1.9", summary = "X11 font encoding library" },
  { name = "libpciaccess", version = "0.17", summary = "Generic PCI access library (X11)" },
  { name = "libxcb", version = "1.17.0", summary = "X C Binding library (X11 protocol client library)" },
  { name = "libxcvt", version = "0.1.3", summary = "Library for VESA CVT standard timing modelines" },
  { name = "libz", version = "1.3.1", summary = "Zlib-compatible shared library (Zeta sample; exercises symlinks)" },
  { name = "mango", version = "0.15.6", summary = "MangoWM: lightweight dwl-based Wayland compositor" },
  { name = "nscde", version = "2.3", summary = "Not so Common Desktop Environment: retro CDE-like desktop on FVWM" },
  { name = "pipewire", version = "1.6.8", summary = "Multimedia processing graph and audio/video daemon" },
  { name = "pixman", version = "0.46.4", summary = "Pixel manipulation library (low-level rendering primitives)" },
  { name = "pulseaudio", version = "17.0", summary = "Network-capable sound server and client library" },
  { name = "scenefx", version = "0.5", summary = "Wayland compositor effects library (window animation/effects)" },
  { name = "util-macros", version = "1.20.2", summary = "X.Org Autoconf macros (build-time dependency)" },
  { name = "wayland", version = "1.26.0", summary = "Wayland compositor infrastructure: client/server libraries and scanner" },
  { name = "wayland-protocols", version = "1.49", summary = "Wayland protocol XML definitions (build-time data for compositors and clients)" },
  { name = "wlroots", version = "0.20.2", summary = "Modular Wayland compositor library" },
  { name = "xauth", version = "1.1.5", summary = "X authority file utility (X11)" },
  { name = "xcb-proto", version = "1.17.0", summary = "XCB protocol descriptions (build-time dependency)" },
  { name = "xinit", version = "1.4.4", summary = "X11 server startup tool (startx/xinit)" },
  { name = "xkbcommon", version = "1.13.2", summary = "Keyboard keymap compiler and support library" },
  { name = "xorg-server", version = "21.1.24", summary = "X.Org X server (modesetting driver, no GLX)" },
  { name = "xorgproto", version = "2025.1", summary = "Combined X.Org protocol headers (build-time dependency)" },
  { name = "xshmfence", version = "1.3.3", summary = "X11 shared memory fence library (synchronization primitives)" },
  { name = "xtrans", version = "1.5.1", summary = "X transport library (headers and pkg-config file, build-time dependency)" },
}